kafka:
  timeout: 5s
  timeout_ms: 10000
  buff: 1
  producer:
    server: "127.0.0.1:9092"
    topic: "brokers-check"
  consumer:
    server: "127.0.0.1:9092"
    topic: "brokers-check"
    group_id: "brokers-check"
    auto_offset_reset: "latest"
